version: '3.8'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  db:
    build: ./database
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5432:6666"

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin!"
    ports:
      - "16543:80"
    depends_on:
      - db
