version: '3.8'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=root
      - DB_USER=root
      - DB_PASS=root
      - APP_PORT=8080
      - NODE_ENV=development
      - ACCESS_TOKEN=qazxswedc
      - REFRESH_TOKEN=qazxswedc
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  db:
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:6666"

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin!"
    ports:
      - "16543:80"
    depends_on:
      - db
